import { CharacterWithFavorite } from '@models/index';

export const mockedCharacter: CharacterWithFavorite = {
  id: '1',
  name: 'Luke Skywalker Mocked',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.dev/api/planets/1/',
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/',
  ],
  species: [],
  vehicles: ['https://swapi.dev/api/vehicles/14/', 'https://swapi.dev/api/vehicles/30/'],
  starships: ['https://swapi.dev/api/starships/12/', 'https://swapi.dev/api/starships/22/'],
  created: '2014-12-09T13:50:51.644000Z',
  edited: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.dev/api/people/1/',
  isFavorite: false,
};

export const mockedDetails: CharacterWithFavorite = {
  id: '1',
  name: 'Luke Skywalker Details',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.dev/api/planets/1/',
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/',
  ],
  species: [],
  vehicles: ['https://swapi.dev/api/vehicles/14/', 'https://swapi.dev/api/vehicles/30/'],
  starships: ['https://swapi.dev/api/starships/12/', 'https://swapi.dev/api/starships/22/'],
  created: '2014-12-09T13:50:51.644000Z',
  edited: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.dev/api/people/1/',
  isFavorite: false,
};

export const characterNotFound = {
  count: 0,
  next: null,
  previous: null,
  results: [],
};

export const mockedCharacters = {
  count: 1,
  next: '',
  previous: '',
  results: [mockedCharacter],
};

export const mockedFilm = {
  title: 'Revenge of the Sith Mocked',
  episode_id: 3,
  opening_crawl:
    'War! The Republic is crumbling\r\nunder attacks by the ruthless\r\nSith Lord, Count Dooku.\r\nThere are heroes on both sides.\r\nEvil is everywhere.\r\n\r\nIn a stunning move, the\r\nfiendish droid leader, General\r\nGrievous, has swept into the\r\nRepublic capital and kidnapped\r\nChancellor Palpatine, leader of\r\nthe Galactic Senate.\r\n\r\nAs the Separatist Droid Army\r\nattempts to flee the besieged\r\ncapital with their valuable\r\nhostage, two Jedi Knights lead a\r\ndesperate mission to rescue the\r\ncaptive Chancellor....',
  director: 'George Lucas',
  producer: 'Rick McCallum',
  release_date: '2005-05-19',
  characters: [
    'https://swapi.dev/api/people/1/',
    'https://swapi.dev/api/people/2/',
    'https://swapi.dev/api/people/3/',
    'https://swapi.dev/api/people/4/',
    'https://swapi.dev/api/people/5/',
    'https://swapi.dev/api/people/6/',
    'https://swapi.dev/api/people/7/',
    'https://swapi.dev/api/people/10/',
    'https://swapi.dev/api/people/11/',
    'https://swapi.dev/api/people/12/',
    'https://swapi.dev/api/people/13/',
    'https://swapi.dev/api/people/20/',
    'https://swapi.dev/api/people/21/',
    'https://swapi.dev/api/people/33/',
    'https://swapi.dev/api/people/35/',
    'https://swapi.dev/api/people/46/',
    'https://swapi.dev/api/people/51/',
    'https://swapi.dev/api/people/52/',
    'https://swapi.dev/api/people/53/',
    'https://swapi.dev/api/people/54/',
    'https://swapi.dev/api/people/55/',
    'https://swapi.dev/api/people/56/',
    'https://swapi.dev/api/people/58/',
    'https://swapi.dev/api/people/63/',
    'https://swapi.dev/api/people/64/',
    'https://swapi.dev/api/people/67/',
    'https://swapi.dev/api/people/68/',
    'https://swapi.dev/api/people/75/',
    'https://swapi.dev/api/people/78/',
    'https://swapi.dev/api/people/79/',
    'https://swapi.dev/api/people/80/',
    'https://swapi.dev/api/people/81/',
    'https://swapi.dev/api/people/82/',
    'https://swapi.dev/api/people/83/',
  ],
  planets: [
    'https://swapi.dev/api/planets/1/',
    'https://swapi.dev/api/planets/2/',
    'https://swapi.dev/api/planets/5/',
    'https://swapi.dev/api/planets/8/',
    'https://swapi.dev/api/planets/9/',
    'https://swapi.dev/api/planets/12/',
    'https://swapi.dev/api/planets/13/',
    'https://swapi.dev/api/planets/14/',
    'https://swapi.dev/api/planets/15/',
    'https://swapi.dev/api/planets/16/',
    'https://swapi.dev/api/planets/17/',
    'https://swapi.dev/api/planets/18/',
    'https://swapi.dev/api/planets/19/',
  ],
  starships: [
    'https://swapi.dev/api/starships/2/',
    'https://swapi.dev/api/starships/32/',
    'https://swapi.dev/api/starships/48/',
    'https://swapi.dev/api/starships/59/',
    'https://swapi.dev/api/starships/61/',
    'https://swapi.dev/api/starships/63/',
    'https://swapi.dev/api/starships/64/',
    'https://swapi.dev/api/starships/65/',
    'https://swapi.dev/api/starships/66/',
    'https://swapi.dev/api/starships/68/',
    'https://swapi.dev/api/starships/74/',
    'https://swapi.dev/api/starships/75/',
  ],
  vehicles: [
    'https://swapi.dev/api/vehicles/33/',
    'https://swapi.dev/api/vehicles/50/',
    'https://swapi.dev/api/vehicles/53/',
    'https://swapi.dev/api/vehicles/56/',
    'https://swapi.dev/api/vehicles/60/',
    'https://swapi.dev/api/vehicles/62/',
    'https://swapi.dev/api/vehicles/67/',
    'https://swapi.dev/api/vehicles/69/',
    'https://swapi.dev/api/vehicles/70/',
    'https://swapi.dev/api/vehicles/71/',
    'https://swapi.dev/api/vehicles/72/',
    'https://swapi.dev/api/vehicles/73/',
    'https://swapi.dev/api/vehicles/76/',
  ],
  species: [
    'https://swapi.dev/api/species/1/',
    'https://swapi.dev/api/species/2/',
    'https://swapi.dev/api/species/3/',
    'https://swapi.dev/api/species/6/',
    'https://swapi.dev/api/species/15/',
    'https://swapi.dev/api/species/19/',
    'https://swapi.dev/api/species/20/',
    'https://swapi.dev/api/species/23/',
    'https://swapi.dev/api/species/24/',
    'https://swapi.dev/api/species/25/',
    'https://swapi.dev/api/species/26/',
    'https://swapi.dev/api/species/27/',
    'https://swapi.dev/api/species/28/',
    'https://swapi.dev/api/species/29/',
    'https://swapi.dev/api/species/30/',
    'https://swapi.dev/api/species/33/',
    'https://swapi.dev/api/species/34/',
    'https://swapi.dev/api/species/35/',
    'https://swapi.dev/api/species/36/',
    'https://swapi.dev/api/species/37/',
  ],
  created: '2014-12-20T18:49:38.403000Z',
  edited: '2014-12-20T20:47:52.073000Z',
  url: 'https://swapi.dev/api/films/6/',
};

export const mockedFilms = {
  count: 1,
  next: '',
  previous: '',
  results: [mockedFilm],
};

export const mockedPlanet = {
  name: 'Tatooine Mocked',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.dev/api/people/1/',
    'https://swapi.dev/api/people/2/',
    'https://swapi.dev/api/people/4/',
    'https://swapi.dev/api/people/6/',
    'https://swapi.dev/api/people/7/',
    'https://swapi.dev/api/people/8/',
    'https://swapi.dev/api/people/9/',
    'https://swapi.dev/api/people/11/',
    'https://swapi.dev/api/people/43/',
    'https://swapi.dev/api/people/62/',
  ],
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/',
  ],
  created: '2014-12-09T13:50:49.641000Z',
  edited: '2014-12-20T20:58:18.411000Z',
  url: 'https://swapi.dev/api/planets/1/',
};
